### ISSUE TITLE
Redis won't connect if sleuth tracing is enabled

### ISSUE THREAD

**Issue by bala-striva** [spring-projects/spring-data-redis#2249]
Using spring-boot 2.6.3 with redis and sleuth enabled the startup will stuck at sending redis `HELLO` command.

When setting `spring.sleuth.redis.enabled` to false to project will start and redis can connect.

Also tried with spring-boot 2.5.9 and it's work there which also uses the same lettuce version as far as I can see.

Example project: https://github.com/bala-striva/redis-tracing

Usage: `./gradlew bootBuildImage && docker-compose down && docker-compose up`

Last messages: 

```
redis-tracing_1  | 2022-01-24 08:13:54.808 DEBUG [,,] 1 --- [llEventLoop-5-1] i.n.util.ResourceLeakDetectorFactory     : Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@478f2e23
redis-tracing_1  | 2022-01-24 08:13:54.862 DEBUG [,,] 1 --- [llEventLoop-5-1] io.lettuce.core.protocol.CommandHandler  : [channel=0x4f8a2b43, [id: 0x4bbdc6cd] (inactive), epid=0x1, chid=0x1] channelRegistered()
redis-tracing_1  | 2022-01-24 08:13:54.925 DEBUG [,,] 1 --- [llEventLoop-5-1] io.netty.resolver.dns.DnsNameResolver    : [id: 0xd4b69c50] RECEIVED: UDP [25029: /127.0.0.11:53], DatagramDnsResponse(from: /127.0.0.11:53, 25029, QUERY(0), NoError(0), RD RA)
redis-tracing_1  | 	DefaultDnsQuestion(redis. IN A)
redis-tracing_1  | 	DefaultDnsRawRecord(redis. 600 IN A 4B)
redis-tracing_1  | 2022-01-24 08:13:54.983 DEBUG [,,] 1 --- [llEventLoop-5-1] io.lettuce.core.protocol.CommandHandler  : [channel=0x4f8a2b43, /192.168.0.2:33566 -> redis/192.168.0.3:6379, epid=0x1, chid=0x1] write(ctx, AsyncCommand [type=HELLO, output=GenericMapOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command], promise)
```

**Comment by mp911de** [comment]
Looks like a deadlock, paging @marcingrzejszczak

**Comment by marcingrzejszczak** [comment]
Can you check the latests Cloud snapshots?

**Comment by bala-striva** [comment]
@marcingrzejszczak with `2021.0.1-SNAPSHOT` the problem still occurs

https://github.com/bala-striva/redis-tracing/commit/8f5e99d9c4f63e5e36dd8bdc6d69bfb42399c252

**Comment by marcingrzejszczak** [comment]
Not good... Thanks for checking it out. I'll look into it ASAP.

**Comment by marcingrzejszczak** [comment]
Fixed in Sleuth. You can check out the latest snapshots.

**Comment by bala-striva** [comment]
Thank you! It's working now with the `2021.0.1-SNAPSHOT` version.

**Comment by bala-striva** [comment]
Should i close this issue or do you have a process for it?

**Comment by mp911de** [comment]
Closing the issue since the problem was addressed with Spring Cloud Sleuth.

**Comment by darshitpp** [comment]
This problem still exists with the below versions

1. `spring-boot-starter-parent` v 2.7.5 (and 2.7.1 too)
2. `spring-cloud-dependencies` v 2021.0.4
3. `spring-boot-starter-data-redis` from the above `spring-boot-starter-parent`
4. `spring-cloud-starter-sleuth` from the above `spring-cloud-dependencies`

Additional Info: I want to integrate sleuth in log4j2, and consequently included the `brave-context-log4j2` as mentioned in this stackoverflow answer: https://stackoverflow.com/a/57987624

This happened yesterday when I was in a hurry, so did not record the full logs, but I do have the following
```
Suppressed: io.lettuce.core.RedisConnectionException: Unable to connect to [127.0.0.1:6379]: java.lang.NullPointerException
```
The exception often seen on logs was `Connection timed out`.

Note that my application works perfectly if I remove the `brave-context-log4j2` dependency (without which log4j2 injection does not work)

Related: https://github.com/spring-cloud/spring-cloud-sleuth/issues/1557
